framework:
    messenger:

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # sync: 'sync://'

        routing:
            'App\Message\AdditionNotification': async
            #Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            #Symfony\Component\Notifier\Message\ChatMessage: async
            #Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
